// <auto-generated />
namespace Warehouse_cosmetics_shope.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddCurrencyAndCheckHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCurrencyAndCheckHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202605221844107_AddCurrencyAndCheckHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
